# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
            
    - name: Run tests and collect coverage
      run: dotnet test --no-build --configuration Debug --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

    #- name: Publish test results
    #  uses: dorny/test-reporter@v1
    #  if: always()
    #  with:
    #    name: 'xUnit Test Results'
    #    path: 'TestResults/*.trx'
    #    reporter: dotnet-trx
    #    threshold-warning: 10% # Warning if more than 10% of tests fail
    #    threshold-error: 25% # Error if more than 25% of tests fail
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    fail-on-empty: 'true'
    #    fail-on-error: 'true'
    #    list-tests: 'all'
