# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - name: Run tests and collect coverage
      run: dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings --logger "trx;LogFileName=testresults.trx"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: './**/coverage.cobertura.xml' # Adjust path as needed
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
